spring:
  application:
    name: SeifenArts

  datasource:
    url: jdbc:postgresql://${RAILWAY_PRIVATE_DOMAIN:postgres.railway.internal}:${PGPORT:5432}/${POSTGRES_DB:railway}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
