spring:
  application:
    name: SeifenArts

  datasource:
    url: jdbc:postgresql://localhost:5432/seifenarts
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true